"""
RAG Document Chat API.

Upload documents (PDF, TXT, or MD), then ask questions grounded in their
content. Retrieval uses sentence embeddings + a persistent Chroma vector
store; answers are generated by Gemini from the retrieved chunks only.

Run with:
    uvicorn main:app --reload
"""

import io
import os

import pdfplumber
from dotenv import load_dotenv
from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from google import genai
from google.genai import types as genai_types
from google.genai.errors import APIError
from pydantic import BaseModel

from rag import ingest_document, list_sources, reset_collection, retrieve_chunks

load_dotenv()

app = FastAPI(title="RAG Document Chat API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_methods=["*"],
    allow_headers=["*"],
)

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-3.6-flash")
gemini_client = genai.Client(api_key=GEMINI_API_KEY) if GEMINI_API_KEY else None

SYSTEM_PROMPT = (
    "You answer questions using only the provided document excerpts. "
    "If the excerpts don't contain the answer, say you don't know instead "
    "of guessing. Keep answers concise."
)


class UploadResponse(BaseModel):
    filename: str
    chunks_added: int
    sources: list[str]


class ChatRequest(BaseModel):
    question: str


class ChatResponse(BaseModel):
    answer: str
    sources: list[str]


def extract_text(filename: str, file_bytes: bytes) -> str:
    if filename.lower().endswith(".pdf"):
        with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
            return "\n".join(page.extract_text() or "" for page in pdf.pages)
    return file_bytes.decode("utf-8", errors="ignore")


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/documents")
def documents():
    return {"sources": list_sources()}


@app.delete("/documents")
def clear_documents():
    reset_collection()
    return {"status": "cleared"}


@app.post("/upload", response_model=UploadResponse)
async def upload(file: UploadFile = File(...)):
    if not file.filename.lower().endswith((".pdf", ".txt", ".md")):
        raise HTTPException(status_code=400, detail="Only PDF, TXT, or MD files are supported")

    file_bytes = await file.read()
    text = extract_text(file.filename, file_bytes)
    if not text.strip():
        raise HTTPException(status_code=400, detail="Could not extract any text from the file")

    chunks_added = ingest_document(file.filename, text)
    return UploadResponse(filename=file.filename, chunks_added=chunks_added, sources=list_sources())


@app.post("/chat", response_model=ChatResponse)
async def chat(req: ChatRequest):
    if not req.question.strip():
        raise HTTPException(status_code=400, detail="Question cannot be empty")

    chunks = retrieve_chunks(req.question)
    if not chunks:
        return ChatResponse(
            answer="No documents have been uploaded yet — upload one first.",
            sources=[],
        )

    if gemini_client is None:
        raise HTTPException(status_code=500, detail="GEMINI_API_KEY is not configured on the server")

    context = "\n\n".join(f"[{c['source']}]\n{c['text']}" for c in chunks)
    prompt = f"Document excerpts:\n\n{context}\n\nQuestion: {req.question}"

    try:
        response = gemini_client.models.generate_content(
            model=GEMINI_MODEL,
            contents=prompt,
            config=genai_types.GenerateContentConfig(
                system_instruction=SYSTEM_PROMPT,
                max_output_tokens=1024,
            ),
        )
    except APIError as exc:
        raise HTTPException(status_code=502, detail=f"Gemini API error: {exc}") from exc

    answer = response.text
    sources = sorted({c["source"] for c in chunks})
    return ChatResponse(answer=answer, sources=sources)
