"""
RAG Document Chat API.

Upload documents (PDF, TXT, or MD), then ask questions grounded in their
content. Retrieval uses sentence embeddings + a persistent Chroma vector
store; answers are generated by Gemini from the retrieved chunks only.

Run with:
    uvicorn main:app --reload
"""

import io
import json
import os
import re

import pdfplumber
from dotenv import load_dotenv
from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from google import genai
from google.genai import types as genai_types
from google.genai.errors import APIError
from pydantic import BaseModel

from rag import (
    delete_source,
    get_document_chunks,
    ingest_document,
    list_sources,
    reset_collection,
    retrieve_chunks,
)

load_dotenv()

app = FastAPI(title="RAG Document Chat API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_methods=["*"],
    allow_headers=["*"],
)

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-3.5-flash-lite")
gemini_client = genai.Client(api_key=GEMINI_API_KEY) if GEMINI_API_KEY else None

SYSTEM_PROMPT = (
    "You're the assistant inside a document-chat app. When document excerpts "
    "are provided below, answer strictly from those excerpts and say you "
    "don't know rather than guessing if they don't cover it. If no excerpts "
    "are provided, the user is just chatting (a greeting, thanks, small talk) "
    "— reply naturally and briefly. Match the user's tone: informal or "
    "casual messages (including slang/Gen-Z phrasing) get a relaxed, "
    "informal reply back, not a stiff formal one. Keep answers concise."
)

# "summarize/explain/what's this about" style commands need the whole document,
# not the handful of chunks a similarity search would return for a vague query.
WHOLE_DOC_INTENT_RE = re.compile(r"\b(summar\w*|overview|tl;?dr|explain)\b", re.IGNORECASE)

FAST_THINKING_BUDGET = 256
DEEP_THINKING_BUDGET = 8192


def find_mentioned_source(question: str, sources: list[str]) -> str | None:
    q = question.lower()
    for source in sources:
        stem = source.rsplit(".", 1)[0].lower()
        if source.lower() in q or (len(stem) > 3 and stem in q):
            return source
    return None


class UploadResponse(BaseModel):
    filename: str
    chunks_added: int
    sources: list[str]


class ChatRequest(BaseModel):
    question: str
    think_longer: bool = False


def extract_text(filename: str, file_bytes: bytes) -> str:
    if filename.lower().endswith(".pdf"):
        with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
            return "\n".join(page.extract_text() or "" for page in pdf.pages)
    return file_bytes.decode("utf-8", errors="ignore")


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/documents")
def documents():
    return {"sources": list_sources()}


@app.delete("/documents")
def clear_documents():
    reset_collection()
    return {"status": "cleared"}


@app.delete("/documents/one")
def delete_document(filename: str):
    delete_source(filename)
    return {"sources": list_sources()}


@app.post("/upload", response_model=UploadResponse)
async def upload(file: UploadFile = File(...)):
    if not file.filename.lower().endswith((".pdf", ".txt", ".md")):
        raise HTTPException(status_code=400, detail="Only PDF, TXT, or MD files are supported")

    file_bytes = await file.read()
    text = extract_text(file.filename, file_bytes)
    if not text.strip():
        raise HTTPException(status_code=400, detail="Could not extract any text from the file")

    chunks_added = ingest_document(file.filename, text)
    return UploadResponse(filename=file.filename, chunks_added=chunks_added, sources=list_sources())


@app.post("/chat")
async def chat(req: ChatRequest):
    if not req.question.strip():
        raise HTTPException(status_code=400, detail="Question cannot be empty")

    if gemini_client is None:
        raise HTTPException(status_code=500, detail="GEMINI_API_KEY is not configured on the server")

    sources = list_sources()
    target = find_mentioned_source(req.question, sources)
    if target:
        chunks = get_document_chunks(target)
    elif WHOLE_DOC_INTENT_RE.search(req.question) and len(sources) == 1:
        chunks = get_document_chunks(sources[0])
    else:
        chunks = retrieve_chunks(req.question)

    if chunks:
        context = "\n\n".join(f"[{c['source']}]\n{c['text']}" for c in chunks)
        prompt = f"Document excerpts:\n\n{context}\n\nQuestion: {req.question}"
    else:
        prompt = req.question

    # Dedupe citations by source file, keeping the first (best-ranked) snippet per file.
    citations = []
    seen = set()
    for c in chunks:
        if c["source"] in seen:
            continue
        seen.add(c["source"])
        snippet = c["text"][:240] + ("…" if len(c["text"]) > 240 else "")
        citations.append({"source": c["source"], "snippet": snippet})

    thinking_budget = DEEP_THINKING_BUDGET if req.think_longer else FAST_THINKING_BUDGET
    max_tokens = 4096 if req.think_longer else 1024
    system_instruction = SYSTEM_PROMPT
    if req.think_longer:
        system_instruction += (
            " The user asked you to think longer about this one — reason through it "
            "carefully and give a more thorough, detailed answer than usual."
        )

    def token_stream():
        # First line is a JSON metadata blob (citations); everything after the
        # first newline is raw streamed answer text.
        yield json.dumps({"citations": citations}) + "\n"
        try:
            stream = gemini_client.models.generate_content_stream(
                model=GEMINI_MODEL,
                contents=prompt,
                config=genai_types.GenerateContentConfig(
                    system_instruction=system_instruction,
                    max_output_tokens=max_tokens,
                    thinking_config=genai_types.ThinkingConfig(thinking_budget=thinking_budget),
                ),
            )
            for event in stream:
                if event.text:
                    yield event.text
        except APIError as exc:
            if exc.code == 429:
                yield "\n\n_Hit the free-tier rate limit — wait a few seconds and try again._"
            else:
                yield f"\n\n_Gemini API error: {exc}_"

    return StreamingResponse(token_stream(), media_type="text/plain")
