"""
AI Document Intelligence Platform API.

Upload documents (PDF, TXT, or MD) into per-user collections, then chat
against one document, several, or a whole collection. Retrieval uses
sentence embeddings + a persistent Chroma vector store scoped per user;
answers are generated by Gemini from the retrieved chunks only, with every
answer exposing exactly which chunks (and, for PDFs, which real page
numbers) it drew from.

Run with:
    uvicorn main:app --reload
"""

from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

import config
from db import init_db
from routers import auth as auth_router
from routers import collections as collections_router
from routers import conversations as conversations_router
from routers import dashboard as dashboard_router
from routers import documents as documents_router
from routers import evaluation as evaluation_router


@asynccontextmanager
async def lifespan(app: FastAPI):
    if config.JWT_SECRET_WAS_GENERATED:
        print(
            "WARNING: JWT_SECRET is not set — using a random secret generated for this "
            "process only. All issued tokens will be invalidated on restart. Set "
            "JWT_SECRET in .env for a real deployment."
        )
    if not config.GEMINI_API_KEY:
        print("WARNING: GEMINI_API_KEY is not set — chat endpoints will return 500 until it's configured.")
    init_db()
    yield


app = FastAPI(title="AI Document Intelligence Platform API", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=config.CORS_ORIGINS,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(auth_router.router)
app.include_router(documents_router.router)
app.include_router(collections_router.router)
app.include_router(conversations_router.router)
app.include_router(dashboard_router.router)
app.include_router(evaluation_router.router)


@app.get("/health")
def health():
    return {"status": "ok"}
