import LegalLayout from './LegalLayout'

export default function TermsAndConditions() {
  return (
    <LegalLayout title="Terms and Conditions">
      <p>
        These terms cover the use of DocMind, an individual student portfolio project built and operated by
        Stephan Wasalathanthrige. By creating an account or using the app, you agree to the terms below.
      </p>

      <h2>What this app is</h2>
      <p>
        DocMind lets you upload documents, organize them into collections, and ask questions that are answered from
        the content you uploaded, with citations back to the source text. It is offered as-is, free of charge, as a
        demonstration of the underlying technology and is not a commercial product with a support contract or
        service-level agreement.
      </p>

      <h2>Your account and responsibilities</h2>
      <ul>
        <li>You are responsible for keeping your login credentials confidential.</li>
        <li>You must only upload documents you have the right to upload and use.</li>
        <li>You must not use the app to upload unlawful content or attempt to disrupt, overload, or gain
          unauthorized access to it.</li>
      </ul>

      <h2>Content and intellectual property</h2>
      <p>
        You retain ownership of any documents you upload. The DocMind application code, design, and branding belong
        to Stephan Wasalathanthrige. Uploading a document does not transfer any rights in it beyond what is
        necessary to store, process, and search it inside the app on your behalf.
      </p>

      <h2>Accuracy of answers</h2>
      <p>
        Chat answers are generated by a third-party AI model (Google Gemini) grounded in the text retrieved from
        your documents. The app is designed to say when it cannot find an answer rather than guess, but AI-generated
        answers can still be incomplete or mistaken. Do not rely on them as a substitute for reading the source
        document yourself, especially for legal, medical, financial, or other high-stakes decisions.
      </p>

      <h2>Third-party services</h2>
      <p>
        The app depends on Google's Gemini API to generate answers. Availability, accuracy, and behavior of that
        service are outside this project's control, and an outage or change to that service can affect the app's
        chat features.
      </p>

      <h2>No payments</h2>
      <p>This app does not process payments and charges nothing to use.</p>

      <h2>Availability and changes</h2>
      <p>
        As a student portfolio project, this app is run on a best-effort basis with no uptime guarantee. Features,
        design, or availability may change or be discontinued at any time without notice.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        The app is provided "as is" without warranties of any kind. To the fullest extent permitted by law, Stephan
        Wasalathanthrige is not liable for any loss or damage arising from your use of the app, including reliance
        on an AI-generated answer or loss of uploaded content.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms can be sent to{' '}
        <a href="mailto:stephanwasalathanthrige@gmail.com">stephanwasalathanthrige@gmail.com</a>.
      </p>

      <p className="legal-note">
        These terms have not been reviewed by a lawyer and are written for a student portfolio project, not a
        commercial service. They should not be treated as legal advice.
      </p>
    </LegalLayout>
  )
}
