import { useEffect, useRef, useState } from 'react'
import './App.css'

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000'

function App() {
  const [sources, setSources] = useState([])
  const [messages, setMessages] = useState([])
  const [question, setQuestion] = useState('')
  const [uploading, setUploading] = useState(false)
  const [sending, setSending] = useState(false)
  const [error, setError] = useState(null)
  const fileInputRef = useRef(null)

  useEffect(() => {
    fetch(`${API_URL}/documents`)
      .then((res) => res.json())
      .then((data) => setSources(data.sources))
      .catch(() => {})
  }, [])

  const handleUpload = async (e) => {
    const file = e.target.files[0]
    if (!file) return
    setError(null)
    setUploading(true)

    const formData = new FormData()
    formData.append('file', file)

    try {
      const res = await fetch(`${API_URL}/upload`, { method: 'POST', body: formData })
      if (!res.ok) {
        const body = await res.json().catch(() => ({}))
        throw new Error(body.detail || `Server responded with ${res.status}`)
      }
      const data = await res.json()
      setSources(data.sources)
    } catch (err) {
      setError(`Could not upload: ${err.message}`)
    } finally {
      setUploading(false)
      if (fileInputRef.current) fileInputRef.current.value = ''
    }
  }

  const handleAsk = async (e) => {
    e.preventDefault()
    if (!question.trim() || sending) return

    const asked = question
    setMessages((prev) => [...prev, { role: 'user', content: asked }])
    setQuestion('')
    setError(null)
    setSending(true)

    try {
      const res = await fetch(`${API_URL}/chat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ question: asked }),
      })
      if (!res.ok) {
        const body = await res.json().catch(() => ({}))
        throw new Error(body.detail || `Server responded with ${res.status}`)
      }
      const data = await res.json()
      setMessages((prev) => [
        ...prev,
        { role: 'assistant', content: data.answer, sources: data.sources },
      ])
    } catch (err) {
      setError(`Could not get an answer: ${err.message}`)
    } finally {
      setSending(false)
    }
  }

  return (
    <main className="page">
      <h1>Chat With Your Documents</h1>
      <p className="subtitle">
        Upload a PDF, TXT, or MD file, then ask questions about it. Answers
        are generated by Claude, grounded only in the chunks retrieved from
        your documents (RAG).
      </p>

      <div className="upload-row">
        <label className="upload-button">
          {uploading ? 'Uploading…' : 'Upload document'}
          <input
            ref={fileInputRef}
            type="file"
            accept=".pdf,.txt,.md"
            onChange={handleUpload}
            disabled={uploading}
            hidden
          />
        </label>
        <div className="sources">
          {sources.length === 0 ? (
            <span className="muted">No documents uploaded yet</span>
          ) : (
            sources.map((s) => (
              <span key={s} className="source-pill">
                {s}
              </span>
            ))
          )}
        </div>
      </div>

      <section className="chat">
        {messages.length === 0 && (
          <p className="muted">Ask a question about an uploaded document to get started.</p>
        )}
        {messages.map((m, i) => (
          <div key={i} className={`bubble ${m.role}`}>
            <p>{m.content}</p>
            {m.sources && m.sources.length > 0 && (
              <p className="bubble-sources">Sources: {m.sources.join(', ')}</p>
            )}
          </div>
        ))}
      </section>

      {error && <p className="error">{error}</p>}

      <form onSubmit={handleAsk} className="ask-form">
        <input
          type="text"
          placeholder="Ask a question about your documents…"
          value={question}
          onChange={(e) => setQuestion(e.target.value)}
          disabled={sending}
        />
        <button type="submit" disabled={sending || !question.trim()}>
          {sending ? 'Thinking…' : 'Ask'}
        </button>
      </form>
    </main>
  )
}

export default App
